name: PowerShell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Windows環境のみを選択

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PowerShell 5.1 manually
        run: |
          $ErrorActionPreference = "Stop"  # エラーが発生した場合に即座に停止
          
          # PowerShell 5.1のインストーラーURL
          $url = "https://github.com/PowerShell/PowerShell/releases/download/v5.1.0.0/PowerShell-5.1.0-win-pscore-x64.msi"
          
          # インストーラーを一時ディレクトリにダウンロード
          $msiPath = "C:\temp\PowerShell-5.1.0-win-pscore-x64.msi"
          Invoke-WebRequest -Uri $url -OutFile $msiPath
          
          # MSI インストーラーで PowerShell 5.1 をインストール
          Start-Process msiexec.exe -ArgumentList "/i", $msiPath, "/quiet", "/norestart" -Wait
          
          # インストール後にバージョン確認
          $psVersion = (Get-Command powershell).FileVersionInfo.ProductVersion
          Write-Host "PowerShell version installed: $psVersion"

      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run tests and generate coverage report
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = ".\Functions.Tests.ps1"
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.Path = ".\Functions.psm1"
          Invoke-Pester -Configuration $config

      - name: Upload coverage report to Codecov
        run: |
          .\codecov.exe -t ${{ secrets.CODECOV_TOKEN }} -f './coverage.xml' -R tmadvs/test0326
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
