name: CI for Pester Tests and Coverage Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2 # PowerShellをセットアップ

      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      - name: Run tests and generate coverage report
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = './Functions.Tests.ps1'
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.Path = './Functions.psm1'
          Invoke-Pester -Configuration $config

      - name: Upload coverage report to Codecov
        run: |
          .\codecov.exe -t ${{ secrets.CODECOV_TOKEN }} -f './coverage.xml' -R tmadvs/test0326
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
