name: PowerShell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Windows環境のみを選択

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # PnP PowerShell モジュールをインストール
      - name: Install PnP PowerShell module
        run: |
          Install-Module -Name PnP.PowerShell -Force -Scope CurrentUser

      # GitHub Secretsから証明書をデコード
      - name: Decode certificate from GitHub Secrets
        run: |
          $certBase64 = "${{ secrets.CERT_PFX }}"
          $certPassword = ConvertTo-SecureString "${{ secrets.CERT_PASSWORD }}" -AsPlainText -Force
          
          # 証明書をファイルとして保存
          [System.IO.File]::WriteAllBytes("mycert.pfx", [Convert]::FromBase64String($certBase64))
          
          Write-Host "Certificate saved as mycert.pfx"

      # 証明書のパスとパスワードを指定してSharePointに接続
      - name: Connect to SharePoint using certificate
        run: |
          $tenantId = "${{ secrets.TENANT_ID }}"
          $clientId = "${{ secrets.CLIENT_ID }}"
          $siteUrl = "https://adstest2025.sharepoint.com"
          
          # 証明書を使用してSharePointに接続
          Connect-PnPOnline -Url $siteUrl -ClientId $clientId -TenantId $tenantId -CertificatePath "mycert.pfx" -CertificatePassword $certPassword
          
          Write-Host "Connected to SharePoint site: $siteUrl"

      # Pesterモジュールをインストール
      - name: Install Pester module
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      # テストを実行してカバレッジレポートを生成
      - name: Run tests and generate coverage report
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = ".\Functions.Tests.ps1"
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.Path = ".\Functions.psm1"
          Invoke-Pester -Configuration $config

      # カバレッジレポートをCodecovにアップロード
      - name: Upload coverage report to Codecov
        run: |
          .\codecov.exe -t ${{ secrets.CODECOV_TOKEN }} -f './coverage.xml' -R tmadvs/test0326
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
