name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Install Pester
      run: Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Install PSScriptAnalyzer
      run: Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck

    - name: Run Pester tests
      run: |
        $PesterPreference = New-PesterConfiguration
        $PesterPreference.Run.Path = ".\PwshCIDemo.Tests"
        $PesterPreference.CodeCoverage.Enabled = $true
        $PesterPreference.CodeCoverage.Path = ".\PwshCIDemo\*.ps*1"
        Invoke-Pester -Configuration $PesterPreference

    - name: Run PSScriptAnalyzer
      run: |
        $issues = Invoke-ScriptAnalyzer -Path ".\PwshCIDemo" -Recurse -OutVariable issues
        $errors = $issues | Where-Object { $_.Severity -eq 'Error' }
        $warnings = $issues | Where-Object { $_.Severity -eq 'Warning' }
        if ($errors) {
            Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
        } else {
            Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}
