name: PowerShell CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Windows環境で実行

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v2

      # PnP.PowerShellのインストール
      - name: Install PnP.PowerShell Version 1.7.0
        run: |
          Install-Module -Name PnP.PowerShell -Force -Scope CurrentUser -RequiredVersion 1.7.0

      # GitHub Secrets から証明書をデコードして保存
      - name: Decode certificate from GitHub Secrets and save as .pfx
        run: |
          # GitHub SecretsからBase64エンコードされた証明書データを取得
          $certBase64 = "${{ secrets.CERT_PFX }}"
          $certPassword = ConvertTo-SecureString "${{ secrets.CERT_PASSWORD }}" -AsPlainText -Force

          # 一時ファイルに証明書を保存
          $certificatePath = Join-Path -Path $env:TEMP -ChildPath "temp_cert.pfx"
          [System.IO.File]::WriteAllBytes($certificatePath, [Convert]::FromBase64String($certBase64))

          Write-Host "証明書ファイルパス: $certificatePath"

          if (-not (Test-Path $certificatePath)) {
              Write-Host "証明書ファイルが生成されませんでした。"
              exit 1
          }
          Write-Host "証明書ファイルが正常に生成されました。"

      # SharePoint Online への接続
      - name: Connect to SharePoint Online using Certificate
        run: |
          $siteUrl = "https://adstest2025.sharepoint.com"
          $tenantId = "${{ secrets.TENANT_ID }}"
          $clientId = "${{ secrets.CLIENT_ID }}"
          $certificatePassword = "${{ secrets.CERT_PASSWORD }}"

          # 接続処理
          try {
              Connect-PnPOnline -Url $siteUrl -Tenant $tenantId -ClientId $clientId -CertificatePath $certificatePath -CertificatePassword (ConvertTo-SecureString -String $certificatePassword -AsPlainText -Force)
              Write-Host "SharePoint Online に接続しました。"
          } catch {
              Write-Host "接続エラー: $($_.Exception.Message)"
              throw $_
          }
        env:
          TENANT_ID: ${{ secrets.TENANT_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CERT_PASSWORD: ${{ secrets.CERT_PASSWORD }}

      # Pesterのインストール
      - name: Install Pester
        run: |
          Install-Module -Name Pester -Force -SkipPublisherCheck

      # Pesterテストの実行
      - name: Run Pester Tests
        run: |
          $config = New-PesterConfiguration
          $config.Run.Path = "./Functions.Tests.ps1"
          $config.CodeCoverage.Enabled = $true
          $config.CodeCoverage.OutputFormat = "JaCoCo"
          $config.CodeCoverage.OutputPath = "./coverage.xml"
          Invoke-Pester -Configuration $config
