name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PowerShell
      uses: actions/setup-powershell@v1

    - name: Install Pester
      run: Install-Module -Name Pester -Force -SkipPublisherCheck

    - name: Install PSScriptAnalyzer
      run: Install-Module -Name PSScriptAnalyzer -Force -SkipPublisherCheck

    - name: Run Pester tests
      run: |
        $PesterPreference = New-PesterConfiguration
        $PesterPreference.Run.Path = ".\Functions.Tests.ps1"
        $PesterPreference.CodeCoverage.Enabled = $true
        $PesterPreference.CodeCoverage.Path = ".\Functions.psm1"
        Invoke-Pester -Configuration $PesterPreference

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
